spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/uap_chatbot
    username: root
    password: toor
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.1
          max-tokens: 300
      embedding:
        options:
          model: text-embedding-3-small
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      pgvector:
        initialize-schema: true
        distance-type: COSINE_DISTANCE
        dimensions: 1536

server:
  port: 8080
