spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.1
          max-tokens: 1000
      embedding:
        options:
          model: text-embedding-3-small
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      pgvector:
        initialize-schema: true
        distance-type: COSINE_DISTANCE
        dimensions: 1536

nasa:
  api:
    url: https://api.nasa.gov/planetary/apod
  api-key: ${NASA_API_KEY:DEMO_KEY}

server:
  port: ${PORT:8080}
